# --------------------------------------------------
FROM debian:12-slim AS build
ARG POETRY_VERSION=1.8.3

RUN apt-get update && \
    apt-get install --no-install-suggests --no-install-recommends --yes \
        python3-venv gcc libpython3-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    # Make a virtualenv with poetry in it
    python3 -m venv /venv && \
    /venv/bin/pip install --upgrade pip setuptools wheel && \
    /venv/bin/pip install "poetry==${POETRY_VERSION}"

WORKDIR /app

# Copy over enough for poetry to recognize the project
COPY pyproject.toml poetry.lock ./

# Use poetry to export a requirements file, and install that into the venv
RUN /venv/bin/poetry export --with-credentials --format requirements.txt \
    --output /requirements.txt && \
    /venv/bin/pip install --disable-pip-version-check -r /requirements.txt && \
    /venv/bin/pip uninstall --yes poetry

# --------------------------------------------------
FROM gcr.io/distroless/python3-debian12:nonroot

WORKDIR /app

COPY . ./
COPY --from=build /venv /venv

WORKDIR /app/fittrackee
ENV FLASK_APP /app/fittrackee

ENTRYPOINT ["/venv/bin/flask"]
CMD run --with-threads -h 0.0.0.0
